--name "Fancy Scripts"
--about README.md
--url-template https://github.com/TheFancyWolf/fancy-scripts/raw/$commit/$path
--ignore README.md
--ignore CHANGELOG.md
--ignore LICENSE
--ignore .gitignore
--ignore .luacheckrc
--ignore .reapack-index.conf
--ignore agents.md
--ignore AGENTS.md
--ignore *.json
--ignore .*
